### PR TITLE
Introduce ocaml implementation

### PR DESCRIPTION
**Pull request by leojrfs**
Hey! here it is, as promised!

The only missing piece is the CI. Altho the project is already prepared (should be plug n play), needs installing by the owner of the [sqids](https://github.com/sqids) organization in github. Should be straightforward, instructions as follows:
https://ocaml.ci.dev/getting-started

### CODE REVIEW

**Comment by leojrfs** [comment]
@4kimov after your invitation to be a collaborator on the `squids` org, Im now taking care of the `ocaml-ci` integration.

**Comment by 4kimov** [comment]
Hey @leojrfs,

Many thanks for the implementation, following up & guidance on how to install! Cool, merged & invited so feel free to push as needed. If you're still missing some permissions, please let me know.

This looks pretty complete to me, well done, besides CI - which you're already taking care of it looks like, is there anything else that's missing?

I'll update the website in the meantime.

**Comment by leojrfs** [comment]
Cheers!

Waiting on approval:
https://github.com/ocurrent/ocaml-ci/pull/918

**Comment by leojrfs** [comment]
opam package: https://github.com/ocaml/opam-repository/pull/25222

**Comment by 4kimov** [comment]
Thank you @leojrfs, well done! 👍

**Comment by leojrfs** [comment]
Just a heads up, due to some issues on packaging and compatibility caught by the ci, I had to do some changes.
In order to keep a clean commit structure (without fixups) for the first release, Ive restructured the whole tree.

**Comment by leojrfs** [comment]
just tagged version `0.1.0` and created a new PR for the introduction of the opam package https://github.com/ocaml/opam-repository/pull/25228

**Pull request merged**
